# Generated by Django 5.0.6 on 2024-05-28 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_alter_book_cover_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='cover_pic',
            field=models.ImageField(default='defoult_cover_pic.jpg', upload_to='books_image'),
        ),
    ]
